### ISSUE TITLE
Send email when user subscribe a membership

### ISSUE THREAD

**Issue by LobeTia** [Schroedinger-Hat/peoplez#28]
User should receive a transactional email when their membership subscription is completed
The email should include details about the membership, expire date and a copy of the receipt for the payment (Stripe invoice can be used)

**Comment by TheJoin95** [comment]
@404answernotfound what was the blocking issue you've encountered on this task?

**Comment by 404answernotfound** [comment]
We are not able to proceed to `screen 4` and `screen 5` which is when the email actually gets sent. This seems to be related to something about `Stripe` but can't be certain

**Comment by 404answernotfound** [comment]
PR up for review #67

**Comment by TheJoin95** [comment]
Closing this as completed
We should write tests tho
